/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessState {
  'requiresInvite' : boolean,
  'isUser' : boolean,
  'isAdmin' : boolean,
}
export interface ActivationTokenInfo {
  'status' : TokenStatus,
  'token' : string,
  'usedAt' : [] | [Time],
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdFor' : Principal,
  'isUsed' : boolean,
}
export type EventType = { 'reRegistered' : null } |
  { 'stolenReported' : null } |
  { 'lostReported' : null } |
  { 'ownershipReleased' : null } |
  { 'ownershipTransferred' : null } |
  { 'foundReported' : null } |
  { 'registered' : null };
export interface IMEIEvent {
  'timestamp' : Time,
  'details' : string,
  'eventType' : EventType,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InviteCodeWithStatus {
  'created' : Time,
  'code' : string,
  'usedAt' : [] | [Time],
  'usedBy' : [] | [Principal],
  'deactivated' : boolean,
  'used' : boolean,
  'paymentNote' : [] | [string],
}
export interface MonthlyReportStats {
  'total' : bigint,
  'monthly' : Array<bigint>,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'notifType' : NotificationType,
  'user' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'relatedIMEI' : [] | [string],
}
export type NotificationType = { 'warning' : null } |
  { 'info' : null } |
  { 'success' : null };
export interface Phone {
  'status' : PhoneStatus,
  'model' : string,
  'owner' : Principal,
  'imei' : string,
  'brand' : string,
}
export type PhoneStatus = { 'stolen' : null } |
  { 'active' : null } |
  { 'lost' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type ReleaseOwnershipReason = { 'other' : string } |
  { 'sold' : null } |
  { 'givenToSomeone' : null } |
  { 'replacedWithNewPhone' : null };
export interface Statistics {
  'lostPhones' : bigint,
  'activePhones' : bigint,
  'theftReportStats' : MonthlyReportStats,
  'statusBreakdown' : StatusBreakdown,
  'totalPhones' : bigint,
  'stolenPhones' : bigint,
}
export interface StatusBreakdown {
  'stolen' : bigint,
  'total' : bigint,
  'active' : bigint,
  'lost' : bigint,
}
export interface TheftReport {
  'imei' : string,
  'reportedBy' : Principal,
  'timestamp' : Time,
  'details' : string,
  'location' : string,
}
export type Time = bigint;
export type TokenStatus = { 'revoked' : null } |
  { 'expired' : null } |
  { 'used' : null } |
  { 'unused' : null };
export interface UserProfile { 'city' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhone' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkImei' : ActorMethod<[string], [] | [PhoneStatus]>,
  'checkUserActivationStatus' : ActorMethod<[], boolean>,
  'clearPin' : ActorMethod<[], undefined>,
  'deactivateInviteCode' : ActorMethod<[string], undefined>,
  'generateActivationToken' : ActorMethod<[Principal], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAccessState' : ActorMethod<[], AccessState>,
  'getActivationTokenHistory' : ActorMethod<[], Array<ActivationTokenInfo>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllTheftReports' : ActorMethod<[], Array<TheftReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIMEIHistory' : ActorMethod<[string], Array<IMEIEvent>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getInviteCodesWithStatus' : ActorMethod<[], Array<InviteCodeWithStatus>>,
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getStatistics' : ActorMethod<[], Statistics>,
  'getUserPhones' : ActorMethod<[Principal], Array<Phone>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPin' : ActorMethod<[], boolean>,
  'hasUserAccess' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'redeemActivationToken' : ActorMethod<[string], undefined>,
  'redeemInviteCode' : ActorMethod<[string], undefined>,
  'registerProfile' : ActorMethod<[string, string], undefined>,
  'releasePhone' : ActorMethod<
    [string, string, ReleaseOwnershipReason],
    undefined
  >,
  'reportFound' : ActorMethod<[string, [] | [string]], undefined>,
  'reportLostStolen' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOrChangePin' : ActorMethod<[string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transferOwnership' : ActorMethod<[string, Principal, string], undefined>,
  'validatePin' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];