/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhoneStatus = IDL.Variant({
  'stolen' : IDL.Null,
  'active' : IDL.Null,
  'lost' : IDL.Null,
});
export const AccessState = IDL.Record({
  'requiresInvite' : IDL.Bool,
  'isUser' : IDL.Bool,
  'isAdmin' : IDL.Bool,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const TheftReport = IDL.Record({
  'imei' : IDL.Text,
  'reportedBy' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'email' : IDL.Text,
});
export const EventType = IDL.Variant({
  'reRegistered' : IDL.Null,
  'stolenReported' : IDL.Null,
  'lostReported' : IDL.Null,
  'ownershipRevoked' : IDL.Null,
  'ownershipReleaseRequested' : IDL.Null,
  'ownershipTransferred' : IDL.Null,
  'foundReported' : IDL.Null,
  'registered' : IDL.Null,
});
export const IMEIEvent = IDL.Record({
  'timestamp' : Time,
  'details' : IDL.Text,
  'eventType' : EventType,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const InviteCodeWithStatus = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'usedAt' : IDL.Opt(Time),
  'usedBy' : IDL.Opt(IDL.Principal),
  'deactivated' : IDL.Bool,
  'used' : IDL.Bool,
  'paymentNote' : IDL.Opt(IDL.Text),
});
export const NotificationType = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'success' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'relatedIMEI' : IDL.Opt(IDL.Text),
});
export const MonthlyReportStats = IDL.Record({
  'total' : IDL.Nat,
  'monthly' : IDL.Vec(IDL.Nat),
});
export const StatusBreakdown = IDL.Record({
  'stolen' : IDL.Nat,
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'lost' : IDL.Nat,
});
export const Statistics = IDL.Record({
  'lostPhones' : IDL.Nat,
  'activePhones' : IDL.Nat,
  'theftReportStats' : MonthlyReportStats,
  'statusBreakdown' : StatusBreakdown,
  'totalPhones' : IDL.Nat,
  'stolenPhones' : IDL.Nat,
});
export const Phone = IDL.Record({
  'status' : PhoneStatus,
  'model' : IDL.Text,
  'owner' : IDL.Principal,
  'imei' : IDL.Text,
  'brand' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhone' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkImei' : IDL.Func([IDL.Text], [IDL.Opt(PhoneStatus)], ['query']),
  'clearPin' : IDL.Func([], [], []),
  'deactivateInviteCode' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAccessState' : IDL.Func([], [AccessState], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllTheftReports' : IDL.Func([], [IDL.Vec(TheftReport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIMEIHistory' : IDL.Func([IDL.Text], [IDL.Vec(IMEIEvent)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getInviteCodesWithStatus' : IDL.Func(
      [],
      [IDL.Vec(InviteCodeWithStatus)],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getStatistics' : IDL.Func([], [Statistics], ['query']),
  'getUserPhones' : IDL.Func([IDL.Principal], [IDL.Vec(Phone)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasPin' : IDL.Func([], [IDL.Bool], ['query']),
  'hasUserAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'redeemInviteCode' : IDL.Func([IDL.Text], [], []),
  'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'releasePhoneFinal' : IDL.Func([IDL.Nat], [], []),
  'reportFound' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'reportLostStolen' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'requestPhoneRelease' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOrChangePin' : IDL.Func([IDL.Text], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'transferOwnership' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'validatePin' : IDL.Func([IDL.Text], [], []),
  'verifyReleaseRequest' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhoneStatus = IDL.Variant({
    'stolen' : IDL.Null,
    'active' : IDL.Null,
    'lost' : IDL.Null,
  });
  const AccessState = IDL.Record({
    'requiresInvite' : IDL.Bool,
    'isUser' : IDL.Bool,
    'isAdmin' : IDL.Bool,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const TheftReport = IDL.Record({
    'imei' : IDL.Text,
    'reportedBy' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'city' : IDL.Text, 'email' : IDL.Text });
  const EventType = IDL.Variant({
    'reRegistered' : IDL.Null,
    'stolenReported' : IDL.Null,
    'lostReported' : IDL.Null,
    'ownershipRevoked' : IDL.Null,
    'ownershipReleaseRequested' : IDL.Null,
    'ownershipTransferred' : IDL.Null,
    'foundReported' : IDL.Null,
    'registered' : IDL.Null,
  });
  const IMEIEvent = IDL.Record({
    'timestamp' : Time,
    'details' : IDL.Text,
    'eventType' : EventType,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const InviteCodeWithStatus = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'usedAt' : IDL.Opt(Time),
    'usedBy' : IDL.Opt(IDL.Principal),
    'deactivated' : IDL.Bool,
    'used' : IDL.Bool,
    'paymentNote' : IDL.Opt(IDL.Text),
  });
  const NotificationType = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'success' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'relatedIMEI' : IDL.Opt(IDL.Text),
  });
  const MonthlyReportStats = IDL.Record({
    'total' : IDL.Nat,
    'monthly' : IDL.Vec(IDL.Nat),
  });
  const StatusBreakdown = IDL.Record({
    'stolen' : IDL.Nat,
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'lost' : IDL.Nat,
  });
  const Statistics = IDL.Record({
    'lostPhones' : IDL.Nat,
    'activePhones' : IDL.Nat,
    'theftReportStats' : MonthlyReportStats,
    'statusBreakdown' : StatusBreakdown,
    'totalPhones' : IDL.Nat,
    'stolenPhones' : IDL.Nat,
  });
  const Phone = IDL.Record({
    'status' : PhoneStatus,
    'model' : IDL.Text,
    'owner' : IDL.Principal,
    'imei' : IDL.Text,
    'brand' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhone' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkImei' : IDL.Func([IDL.Text], [IDL.Opt(PhoneStatus)], ['query']),
    'clearPin' : IDL.Func([], [], []),
    'deactivateInviteCode' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAccessState' : IDL.Func([], [AccessState], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllTheftReports' : IDL.Func([], [IDL.Vec(TheftReport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIMEIHistory' : IDL.Func([IDL.Text], [IDL.Vec(IMEIEvent)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getInviteCodesWithStatus' : IDL.Func(
        [],
        [IDL.Vec(InviteCodeWithStatus)],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getStatistics' : IDL.Func([], [Statistics], ['query']),
    'getUserPhones' : IDL.Func([IDL.Principal], [IDL.Vec(Phone)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasPin' : IDL.Func([], [IDL.Bool], ['query']),
    'hasUserAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'redeemInviteCode' : IDL.Func([IDL.Text], [], []),
    'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'releasePhoneFinal' : IDL.Func([IDL.Nat], [], []),
    'reportFound' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'reportLostStolen' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'requestPhoneRelease' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOrChangePin' : IDL.Func([IDL.Text], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'transferOwnership' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'validatePin' : IDL.Func([IDL.Text], [], []),
    'verifyReleaseRequest' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };