/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReportStats {
    total: bigint;
    monthly: Array<bigint>;
}
export interface TheftReport {
    imei: string;
    reportedBy: Principal;
    timestamp: Time;
    details: string;
    location: string;
}
export type Time = bigint;
export interface Statistics {
    lostPhones: bigint;
    activePhones: bigint;
    theftReportStats: MonthlyReportStats;
    statusBreakdown: StatusBreakdown;
    totalPhones: bigint;
    stolenPhones: bigint;
}
export interface Phone {
    status: PhoneStatus;
    model: string;
    owner: Principal;
    imei: string;
    brand: string;
}
export interface InviteCodeWithStatus {
    created: Time;
    code: string;
    usedAt?: Time;
    usedBy?: Principal;
    deactivated: boolean;
    used: boolean;
    paymentNote?: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface AccessState {
    requiresInvite: boolean;
    isUser: boolean;
    isAdmin: boolean;
}
export interface Notification {
    id: bigint;
    title: string;
    notifType: NotificationType;
    user: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedIMEI?: string;
}
export interface StatusBreakdown {
    stolen: bigint;
    total: bigint;
    active: bigint;
    lost: bigint;
}
export interface IMEIEvent {
    timestamp: Time;
    details: string;
    eventType: EventType;
}
export interface UserProfile {
    city: string;
    email: string;
}
export enum EventType {
    reRegistered = "reRegistered",
    stolenReported = "stolenReported",
    lostReported = "lostReported",
    ownershipRevoked = "ownershipRevoked",
    ownershipReleaseRequested = "ownershipReleaseRequested",
    ownershipTransferred = "ownershipTransferred",
    foundReported = "foundReported",
    registered = "registered"
}
export enum NotificationType {
    warning = "warning",
    info = "info",
    success = "success"
}
export enum PhoneStatus {
    stolen = "stolen",
    active = "active",
    lost = "lost"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPhone(imei: string, brand: string, model: string, pin: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkImei(imei: string): Promise<PhoneStatus | null>;
    clearPin(): Promise<void>;
    deactivateInviteCode(inviteCode: string): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAccessState(): Promise<AccessState>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllTheftReports(): Promise<Array<TheftReport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIMEIHistory(imei: string): Promise<Array<IMEIEvent>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getInviteCodesWithStatus(): Promise<Array<InviteCodeWithStatus>>;
    getNotifications(user: Principal): Promise<Array<Notification>>;
    getStatistics(): Promise<Statistics>;
    getUserPhones(user: Principal): Promise<Array<Phone>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasPin(): Promise<boolean>;
    hasUserAccess(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsAsRead(): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    redeemInviteCode(inviteCode: string): Promise<void>;
    registerProfile(email: string, city: string): Promise<void>;
    releasePhoneFinal(requestId: bigint): Promise<void>;
    reportFound(imei: string, finderInfo: string | null): Promise<void>;
    reportLostStolen(imei: string, location: string, details: string, isStolen: boolean): Promise<void>;
    requestPhoneRelease(imei: string, reason: string, pin: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setOrChangePin(newPin: string): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    transferOwnership(imei: string, newOwner: Principal): Promise<void>;
    validatePin(pin: string): Promise<void>;
    verifyReleaseRequest(requestId: bigint): Promise<void>;
}
import type { EventType as _EventType, IMEIEvent as _IMEIEvent, InviteCodeWithStatus as _InviteCodeWithStatus, Notification as _Notification, NotificationType as _NotificationType, Phone as _Phone, PhoneStatus as _PhoneStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPhone(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhone(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhone(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkImei(arg0: string): Promise<PhoneStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkImei(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkImei(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearPin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPin();
            return result;
        }
    }
    async deactivateInviteCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateInviteCode(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAccessState(): Promise<AccessState> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessState();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllTheftReports(): Promise<Array<TheftReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTheftReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTheftReports();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIMEIHistory(arg0: string): Promise<Array<IMEIEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIMEIHistory(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIMEIHistory(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getInviteCodesWithStatus(): Promise<Array<InviteCodeWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodesWithStatus();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodesWithStatus();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatistics(): Promise<Statistics> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics();
            return result;
        }
    }
    async getUserPhones(arg0: Principal): Promise<Array<Phone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPhones(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPhones(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPin();
            return result;
        }
    }
    async hasUserAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserAccess();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsAsRead();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async redeemInviteCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemInviteCode(arg0);
            return result;
        }
    }
    async registerProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, arg1);
            return result;
        }
    }
    async releasePhoneFinal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releasePhoneFinal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releasePhoneFinal(arg0);
            return result;
        }
    }
    async reportFound(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportFound(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportFound(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async reportLostStolen(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportLostStolen(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportLostStolen(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async requestPhoneRelease(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPhoneRelease(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPhoneRelease(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setOrChangePin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOrChangePin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOrChangePin(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async transferOwnership(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferOwnership(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferOwnership(arg0, arg1);
            return result;
        }
    }
    async validatePin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePin(arg0);
            return result;
        }
    }
    async verifyReleaseRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyReleaseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyReleaseRequest(arg0);
            return result;
        }
    }
}
function from_candid_EventType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IMEIEvent_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IMEIEvent): IMEIEvent {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCodeWithStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCodeWithStatus): InviteCodeWithStatus {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PhoneStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhoneStatus): PhoneStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Phone_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Phone): Phone {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhoneStatus]): PhoneStatus | null {
    return value.length === 0 ? null : from_candid_PhoneStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timestamp: _Time;
    details: string;
    eventType: _EventType;
}): {
    timestamp: Time;
    details: string;
    eventType: EventType;
} {
    return {
        timestamp: value.timestamp,
        details: value.details,
        eventType: from_candid_EventType_n12(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    code: string;
    usedAt: [] | [_Time];
    usedBy: [] | [Principal];
    deactivated: boolean;
    used: boolean;
    paymentNote: [] | [string];
}): {
    created: Time;
    code: string;
    usedAt?: Time;
    usedBy?: Principal;
    deactivated: boolean;
    used: boolean;
    paymentNote?: string;
} {
    return {
        created: value.created,
        code: value.code,
        usedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.usedAt)),
        usedBy: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.usedBy)),
        deactivated: value.deactivated,
        used: value.used,
        paymentNote: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.paymentNote))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notifType: _NotificationType;
    user: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedIMEI: [] | [string];
}): {
    id: bigint;
    title: string;
    notifType: NotificationType;
    user: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedIMEI?: string;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotificationType_n23(_uploadFile, _downloadFile, value.notifType),
        user: value.user,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp,
        relatedIMEI: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.relatedIMEI))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PhoneStatus;
    model: string;
    owner: Principal;
    imei: string;
    brand: string;
}): {
    status: PhoneStatus;
    model: string;
    owner: Principal;
    imei: string;
    brand: string;
} {
    return {
        status: from_candid_PhoneStatus_n4(_uploadFile, _downloadFile, value.status),
        model: value.model,
        owner: value.owner,
        imei: value.imei,
        brand: value.brand
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reRegistered: null;
} | {
    stolenReported: null;
} | {
    lostReported: null;
} | {
    ownershipRevoked: null;
} | {
    ownershipReleaseRequested: null;
} | {
    ownershipTransferred: null;
} | {
    foundReported: null;
} | {
    registered: null;
}): EventType {
    return "reRegistered" in value ? EventType.reRegistered : "stolenReported" in value ? EventType.stolenReported : "lostReported" in value ? EventType.lostReported : "ownershipRevoked" in value ? EventType.ownershipRevoked : "ownershipReleaseRequested" in value ? EventType.ownershipReleaseRequested : "ownershipTransferred" in value ? EventType.ownershipTransferred : "foundReported" in value ? EventType.foundReported : "registered" in value ? EventType.registered : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    success: null;
}): NotificationType {
    return "warning" in value ? NotificationType.warning : "info" in value ? NotificationType.info : "success" in value ? NotificationType.success : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stolen: null;
} | {
    active: null;
} | {
    lost: null;
}): PhoneStatus {
    return "stolen" in value ? PhoneStatus.stolen : "active" in value ? PhoneStatus.active : "lost" in value ? PhoneStatus.lost : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteCodeWithStatus>): Array<InviteCodeWithStatus> {
    return value.map((x)=>from_candid_InviteCodeWithStatus_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Phone>): Array<Phone> {
    return value.map((x)=>from_candid_Phone_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IMEIEvent>): Array<IMEIEvent> {
    return value.map((x)=>from_candid_IMEIEvent_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
